name: Github Pages Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        working-directory: ./todo-list
        run: npm install && npm run gh-build && cp dist/todolist/index.html dist/todolist/404.html

      - name: Deploy
        uses: rashaeldebeeky/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: todo-list/dist/todolist # The folder the action should deploy.
