name: Github Pages Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
         npm install && npm run gh-build

    - name: Deploy
        uses: rashaeldebeeky/github-pages-deploy-action@4.1.1
        with:
          branch: main 
          folder: ./dist/todolist 
